import pytest
import numpy as np
from analysis.three_phase import analyze_three_phase
from analysis.pwm import analyze_pwm


def test_center_aligned_pwm_output_edge_displacement():
    """
    PHYSICAL PRINCIPLE PROOF:
    In center-aligned symmetric ePWM (TMS320F28P65 Up-Down count mode),
    the time-base counters (TBCTR) are 100% phase-synchronized.
    However, rising and falling edges are generated by comparison with CMPA/CMPB.
    When duties differ across phases (e.g. Du=80%, Dv=50%, Dw=20%):
      - U rising edge: (1.0 - 0.80) / 2 = 10% into switching period
      - V rising edge: (1.0 - 0.50) / 2 = 25% into switching period
      - W rising edge: (1.0 - 0.20) / 2 = 40% into switching period
    The difference between U and W rising edges is 30% of the switching period (18.75 us at 16 kHz)!
    This proves that using output rising edge distances to measure carrier synchronization
    is mathematically and physically false for center-aligned PWM.

    This test verifies:
      1. analyze_three_phase reports carrier_phase_status == 'NOT_MEASURED'.
      2. carrier_is_synchronized is None.
      3. Switching frequency consistency is verified (carrier_frequency_diff_max_hz ~ 0).
      4. Per-channel duty extraction accurately recovers 80%, 50%, 20% without cross-contamination.
    """
    sample_rate = 10_000_000.0  # 10 MHz (100 ns resolution)
    f_sw = 16_000.0            # 16 kHz carrier (period = 625 samples = 62.5 us)
    period_samples = int(round(sample_rate / f_sw))
    n_cycles = 60
    total = period_samples * n_cycles

    u_bits = np.zeros(total, dtype=np.uint8)
    v_bits = np.zeros(total, dtype=np.uint8)
    w_bits = np.zeros(total, dtype=np.uint8)

    # Center-aligned high pulses
    # Phase U: 80% duty -> high for 500 samples, centered in 625 -> starts at 62, ends at 562
    u_high = int(round(0.80 * period_samples))
    u_start = (period_samples - u_high) // 2

    # Phase V: 50% duty -> high for 312 samples, centered in 625 -> starts at 156, ends at 468
    v_high = int(round(0.50 * period_samples))
    v_start = (period_samples - v_high) // 2

    # Phase W: 20% duty -> high for 125 samples, centered in 625 -> starts at 250, ends at 375
    w_high = int(round(0.20 * period_samples))
    w_start = (period_samples - w_high) // 2

    for k in range(n_cycles):
        base = k * period_samples
        u_bits[base + u_start : base + u_start + u_high] = 1
        v_bits[base + v_start : base + v_start + v_high] = 1
        w_bits[base + w_start : base + w_start + w_high] = 1

    u_b = np.packbits(u_bits, bitorder='little').tobytes()
    v_b = np.packbits(v_bits, bitorder='little').tobytes()
    w_b = np.packbits(w_bits, bitorder='little').tobytes()

    res = analyze_three_phase(u_b, v_b, w_b, sample_rate)

    # Carrier phase is NOT_MEASURED because no dedicated reference was provided
    assert res.carrier.carrier_phase_status == 'NOT_MEASURED'
    assert res.carrier.carrier_is_synchronized is None

    # Frequency consistency is verified
    assert abs(res.carrier.carrier_frequency_mean_hz - 16000.0) < 50.0
    assert res.carrier.carrier_frequency_diff_max_hz < 10.0

    # Independent per-channel duty cycle extraction accuracy
    assert abs(res.pwm_u.duty_cycle_mean - 0.80) < 0.01
    assert abs(res.pwm_v.duty_cycle_mean - 0.50) < 0.01
    assert abs(res.pwm_w.duty_cycle_mean - 0.20) < 0.01

    # Individual channels are valid and anomaly-free
    assert res.pwm_u.measurement_valid is True
    assert res.pwm_u.anomaly_free is True
    assert res.pwm_u.valid is True
    assert res.pwm_v.valid is True
    assert res.pwm_w.valid is True


def test_center_aligned_pwm_with_dedicated_carrier_reference():
    """
    Verify that when a dedicated hardware carrier reference channel (e.g. EPWM11 / CarrierSync
    pulsed at TBCTR=0) is provided, center-aligned PWM achieves SYNCHRONIZED status.
    """
    sample_rate = 10_000_000.0
    f_sw = 16_000.0
    period_samples = int(round(sample_rate / f_sw))
    n_cycles = 60
    total = period_samples * n_cycles

    u_bits = np.zeros(total, dtype=np.uint8)
    v_bits = np.zeros(total, dtype=np.uint8)
    w_bits = np.zeros(total, dtype=np.uint8)
    ref_bits = np.zeros(total, dtype=np.uint8)

    u_high = int(round(0.60 * period_samples))
    u_start = (period_samples - u_high) // 2

    for k in range(n_cycles):
        base = k * period_samples
        u_bits[base + u_start : base + u_start + u_high] = 1
        v_bits[base + u_start : base + u_start + u_high] = 1
        w_bits[base + u_start : base + u_start + u_high] = 1
        # Dedicated hardware reference pulse at TBCTR=0
        ref_bits[base : base + 10] = 1

    u_b = np.packbits(u_bits, bitorder='little').tobytes()
    v_b = np.packbits(v_bits, bitorder='little').tobytes()
    w_b = np.packbits(w_bits, bitorder='little').tobytes()
    ref_b = np.packbits(ref_bits, bitorder='little').tobytes()

    res = analyze_three_phase(u_b, v_b, w_b, sample_rate, carrier_ref_raw=ref_b)
    assert res.carrier.carrier_phase_status == 'SYNCHRONIZED'
    assert res.carrier.carrier_is_synchronized is True
    assert res.valid is True


def test_center_aligned_pwm_anomaly_detection():
    """
    Verify that PWM state split (measurement_valid vs anomaly_free vs valid)
    correctly flags anomalies (e.g. missing pulse or extra glitch) even when cycle count is sufficient.
    """
    sample_rate = 10_000_000.0
    f_sw = 10_000.0
    period_samples = 1000
    n_cycles = 20
    total = period_samples * n_cycles

    bits = np.zeros(total, dtype=np.uint8)
    for k in range(n_cycles):
        base = k * period_samples
        if k == 10:
            # Drop pulse at cycle 10 (missing pulse anomaly)
            continue
        # 50% duty centered
        bits[base + 250 : base + 750] = 1

    raw = np.packbits(bits, bitorder='little').tobytes()
    meas = analyze_pwm(raw, sample_rate, channel=0)

    # Has >= 5 cycles so measurement_valid is True
    assert meas.measurement_valid is True
    # But dropped a pulse, so anomaly_free is False
    assert meas.anomaly_free is False
    assert meas.missing_pulse_count >= 1
    # Overall valid must be False
    assert meas.valid is False

